name: GitHub CI
on:
  push:
    branches:
      - main
    
jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
     - name: Checkout
       uses: actions/checkout@v2
     
     - name: Build KinuxOS
       run: |
         chmod +x ./build-os/build.sh
         ./build-os/build.sh
