name: GitHub CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
     - name: Checkout
       uses: actions/checkout@v2
    
     - name: Build KinuxOS
       run: |
         sudo build-os/build.sh
      
     - name: Upload Build Artifacts
       uses: actions/upload-artifact@v2
       with:
         name: build
         path: build/
  
